# Generated by Django 4.1.4 on 2022-12-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardGenerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_series', models.CharField(max_length=50, verbose_name='Серия карты')),
                ('number_card', models.IntegerField(verbose_name='Номер карты')),
                ('card_issue_date', models.DateTimeField(db_index=True, verbose_name='Дата выпуска карты')),
                ('end_date_of_card_activity', models.DateTimeField(db_index=True, verbose_name='Дата окончания активности карты')),
                ('card_use_date', models.DateTimeField(db_index=True, verbose_name='Дата использования')),
                ('amount_on_the_card', models.FloatField(verbose_name='Сумма на карте в руб.')),
                ('card_status', models.CharField(choices=[('not_activated', 'Не активирована'), ('activated', 'Активирована'), ('overdue', 'Просрочена')], max_length=50, verbose_name='Статус карты')),
            ],
            options={
                'verbose_name': 'Карты',
                'verbose_name_plural': 'Карты',
                'ordering': ['-card_issue_date'],
            },
        ),
    ]
