# Generated by Django 4.1.4 on 2022-12-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardgenerator',
            name='amount_on_the_card',
            field=models.FloatField(verbose_name='Сумма на карте'),
        ),
        migrations.AlterField(
            model_name='cardgenerator',
            name='number_card',
            field=models.IntegerField(verbose_name='Номер карты'),
        ),
    ]
