# Generated by Django 4.1.4 on 2022-12-09 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card_generator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardgenerator',
            name='card_use_date',
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_use_date', models.DateTimeField(db_index=True, verbose_name='Дата использования')),
                ('card_generator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='card_generator.cardgenerator')),
            ],
            options={
                'ordering': ['-card_use_date'],
            },
        ),
    ]
