# Generated by Django 4.1.4 on 2022-12-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_generator', '0004_alter_cardgenerator_card_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardgenerator',
            name='card_status',
            field=models.CharField(choices=[('Не активирована', 'Не активирована'), ('activated', 'Активирована'), ('overdue', 'Просрочена')], max_length=50, verbose_name='Статус карты'),
        ),
    ]
