# Generated by Django 4.1.4 on 2022-12-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_generator', '0014_remove_cardgenerator_overdue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardgenerator',
            name='number_card',
            field=models.CharField(max_length=50, verbose_name='Номер карты'),
        ),
    ]
